# Generated by Django 5.1.2 on 2024-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="")),
                ("desc", models.CharField(max_length=500)),
            ],
        ),
    ]
