# Generated by Django 5.1.2 on 2024-11-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="app/static/images/urbex-icon.png", upload_to="images/test/"
            ),
        ),
    ]
