# Generated by Django 4.2.16 on 2024-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lat",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="long",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
